POST http://localhost:4004/service/PRMService/Contacts
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Kennedy",
    "Email": "john.kennedy@abc.com",
    "Function": "E_signer",
    "partner_ID": "a1719c78-3b2d-4ff1-bcf4-dc0ed89bece9"
}