
@host = http://localhost:4004
@service = {{host}}/service/PRMServiceAPI

POST {{service}}/Partners
Content-Type: application/json

{
    "Name": "Infocon",
    "Status": "Active",
    "Level": "Gold",

    "contacts": [
        {
            "FirstName": "John",
            "LastName": "Smith",
            "Email": "john@abc.com",
            "Function": "E_signer"
        },
        {
            "FirstName": "Mary",
            "LastName": "Jones",
            "Email": "mary@abc.com",
            "Function": "Partner_Manager"
        }
    ],

    "memberships": [
        {
            "Type": "Sell",
            "Status": "Authorized",
            "ValidFrom": "2026-07-15",
            "ValidTo": "2030-12-31",

            "dimensions": [
                {
                    "Type": "SERP",
                    "Status": "AUT",
                    "ValidFrom": "2026-07-15",
                    "ValidTo": "2030-12-31"
                }
            ],

            "descriptors": [
                {
                    "Descriptor": "HPE",
                    "ValidFrom": "2026-07-15",
                    "ValidTo": "2030-12-31"
                }
            ]
        }
    ]
}