POST http://localhost:4004/service/PRMService/Memberships
Content-Type: application/json

{
    "ValidTo": "9999-12-31",
    "ValidFrom": "2023-01-01",
    "Type": "Build",
    "Status": "Requested",
    "Reason": "New membership request",
    "partner_ID": "a1719c78-3b2d-4ff1-bcf4-dc0ed89bece9"
}

